import type { TeamMember } from './types'

export const TEAM_MEMBERS: TeamMember[] = [
  {
    id: 'lukasz-mazurowski',
    slug: 'lukasz-mazurowski',
    name: 'Łukasz Mazurowski',
    role: 'Partner Zarządzający',
    roleEN: 'Managing Partner',
    yearsExperience: '20+',
    imageUrl: 'https://profitia.pl/images/profitia/zespol/Lukasz_Mazurowski_crop%204.jpg',
    bio: 'Współzałożyciel Profitii i architekt podejścia intelligence-first w zakupach. Ponad 20 lat doświadczenia w strategicznym doradztwie zakupowym, przygotowaniu do negocjacji i transformacji procesów zakupowych w największych polskich firmach. Łączy precyzję analityczną z praktycznym doświadczeniem stołu negocjacyjnego.',
    bioEN: 'Co-founder of Profitia and architect of the intelligence-first procurement approach. Over 20 years of experience in strategic procurement advisory, negotiation preparation and procurement transformation in Poland\'s largest companies. Combines analytical precision with practical negotiation table experience.',
    areas: ['Strategia zakupowa', 'Negocjacje', 'Transformacja'],
    areasEN: ['Procurement Strategy', 'Negotiations', 'Transformation'],
    type: 'leadership',
    featured: true,
    order: 1,
  },
  {
    id: 'mariusz-turek',
    slug: 'mariusz-turek',
    name: 'Mariusz Turek',
    role: 'Partner',
    roleEN: 'Partner',
    credentials: 'MCIPS',
    yearsExperience: '20+',
    imageUrl: 'https://profitia.pl/images/stopka/Mariusz-Turek.png',
    bio: 'Partner z certyfikatem MCIPS - najwyższym poziomem kwalifikacji CIPS. Ponad 20 lat doświadczenia w strategii zakupowej, analizie wydatków i zarządzaniu dostawcami. Odpowiedzialny za rozwój oferty certyfikacyjnej i standardów zakupowych Profitia. Autor publikacji branżowych i akademickich z obszaru zarządzania zakupami.',
    bioEN: 'Partner with MCIPS certification - the highest level of CIPS qualification. Over 20 years of experience in procurement strategy, spend analysis and supplier management. Responsible for developing Profitia\'s certification offer and procurement standards. Author of industry and academic publications in procurement management.',
    areas: ['CIPS', 'Analityka zakupowa', 'Łańcuch dostaw'],
    areasEN: ['CIPS', 'Spend Analytics', 'Supply Chain'],
    type: 'leadership',
    featured: true,
    order: 2,
  },
  {
    id: 'monika-osiecka',
    slug: 'monika-osiecka',
    name: 'Monika Osiecka',
    role: 'Director · People & Culture',
    roleEN: 'Director · People & Culture',
    yearsExperience: '15+',
    imageUrl: 'https://profitia.pl/images/stopka/Monika-Osiecka.png',
    bio: 'Odpowiedzialna za rozwój kompetencji, programy szkoleniowe i kulturę organizacyjną Profitia. 15+ lat doświadczenia w zarządzaniu rozwojem organizacyjnym, projektowaniu programów certyfikacyjnych i budowaniu zespołów zakupowych. Prowadzi polskie programy CIPS i akademię zakupową Profitia.',
    bioEN: 'Leads capability development, training programs and organizational culture at Profitia. 15+ years of experience in organizational development, certification program design and procurement team building. Runs CIPS programs in Poland and the Profitia procurement academy.',
    areas: ['CIPS', 'Szkolenia', 'Rozwój kompetencji'],
    areasEN: ['CIPS', 'Training', 'Capability Development'],
    type: 'director',
    featured: true,
    order: 3,
  },
  {
    id: 'agnieszka-tworzynska',
    slug: 'agnieszka-tworzynska',
    name: 'Agnieszka Tworzyńska',
    role: 'Training & Conferences',
    roleEN: 'Training & Conferences',
    type: 'trainer',
    featured: false,
    order: 4,
  },
  {
    id: 'tomasz-uscinski',
    slug: 'tomasz-uscinski',
    name: 'Tomasz Uściński',
    role: 'Head of Sales · SpendGuru',
    roleEN: 'Head of Sales · SpendGuru',
    email: 'tomasz.uscinski@profitia.pl',
    type: 'expert',
    featured: false,
    order: 5,
  },
]

/** Leadership and featured directors shown on About page */
export const FEATURED_TEAM: TeamMember[] = TEAM_MEMBERS.filter((m) => m.featured)
