import type { TeamMember } from './types'

export const TEAM_MEMBERS: TeamMember[] = [
  {
    id: 'lukasz-mazurowski',
    slug: 'lukasz-mazurowski',
    name: 'Łukasz Mazurowski',
    role: 'Partner Zarządzający',
    roleEN: 'Managing Partner',
    imageUrl: '/images/website/Lukasz Mazurowski.png',
    imagePosition: '50% 12%',
    linkedin: 'https://www.linkedin.com/in/lukasz-mazurowski-149276/',
    bio: 'Doświadczenie zawodowe w krajowych i międzynarodowych firmach w sektorze doradztwa zakupowego i strategicznego.',
    bioEN: 'Professional experience with Polish and international firms in procurement and strategy consulting.',
    areas: ['Branża naftowa, gazownicza i energetyczna', 'Kompleksowa restrukturyzacja zakupów', 'Programy oszczędnościowe', 'Zarządzanie zmianą w zakupach'],
    areasEN: ['Oil, gas and energy sector', 'Comprehensive procurement restructuring', 'Savings programmes', 'Change management in procurement'],
    selectedExperience: [
      'Restrukturyzacja, rozwój i wdrożenie koncepcji centralizacji zakupów w organizacji na dużą skalę, w tym wprowadzenie koncepcji Kupca Wiodącego',
      'Zabezpieczenie oszczędności na poziomie 300 mln zł dla grupy kapitałowej z branży petrochemicznej działającej w Polsce, Litwie, Czechach i Niemczech',
      'Program Kompleksowej Poprawy Operacji - Comprehensive Operations Improvement Program - dla przedsiębiorstwa petrochemicznego w Czechach',
      'Sourcing strategiczny w kategorii Chemikalia - osiągnięte oszczędności 10% przy 6 mln EUR rocznych wydatków - dla wiodącego przedsiębiorstwa petrochemicznego w Polsce',
      'Prowadzenie zajęć w Szkole Głównej Handlowej z zakresu Strategii Zakupowych oraz Procesów Zakupowych - Katedra Logistyki SGH',
    ],
    selectedExperienceEN: [
      'Restructuring, development and implementation of a large-scale procurement centralisation model, including the introduction of the Lead Buyer concept',
      'Securing PLN 300 million in savings for a petrochemical group operating in Poland, Lithuania, the Czech Republic and Germany',
      'Comprehensive Operations Improvement Program for a petrochemical company in the Czech Republic',
      'Strategic sourcing in the Chemicals category - 10% savings achieved on EUR 6 million in annual spend - for a leading petrochemical company in Poland',
      'Lecturing at the SGH Warsaw School of Economics on Procurement Strategies and Procurement Processes - Department of Logistics',
    ],
    type: 'leadership', featured: true, order: 1,
  },
  {
    id: 'mariusz-turek', slug: 'mariusz-turek', name: 'Mariusz Turek', role: 'Partner', roleEN: 'Partner', credentials: 'MCIPS',
    imageUrl: '/images/website/Mariusz Turek.png', imagePosition: '50% 12%', linkedin: 'https://www.linkedin.com/in/mariuszturek/',
    bio: 'Doświadczenie biznesowe w lokalnych i międzynarodowych firmach w sektorze doradztwa w zakresie zarządzania.',
    bioEN: 'Business experience with local and international management consulting firms.',
    areas: ['Branża naftowa, gazownicza i energetyczna', 'Logistyka', 'FMCG', 'Ocena i wdrażanie strategii zakupowych', 'Mapowanie i usprawnianie procesów', 'Integracja po fuzji', 'Restrukturyzacja', 'Analizy due diligence', 'Modelowanie finansowe'],
    areasEN: ['Oil, gas and energy sector', 'Logistics', 'FMCG', 'Assessment and implementation of procurement strategies', 'Process mapping and improvement', 'Post-merger integration', 'Restructuring', 'Due diligence analysis', 'Financial modelling'],
    selectedExperience: [
      'Udoskonalenia w zakresie zamówień u światowego lidera w przetwórstwie nasion oleistych i największego na świecie producenta olejów - rozwój drzewa wydatków zakupowych, identyfikacja potencjału oszczędności i strategie sourcingowe w wybranych kategoriach dla 12 krajów regionu EMEA',
      'Centralizacja zamówień dla wiodącego polskiego producenta z branży motoryzacyjnej - rozwój centralnego drzewa wydatków zakupowych, analiza wydatków, opracowanie strategii sourcingowych i wdrażanie oszczędności w wielu kategoriach',
      'Optymalizacja zakupów dla spółki przemysłu spożywczego - analiza wydatków, kategoryzacja, strategie sourcingowe i wdrożenie 5,9 mln zł oszczędności rocznie',
      'Restrukturyzacja i wdrożenie koncepcji zakupów centralnych, wraz z zabezpieczeniem oszczędności w wysokości 300 mln PLN',
      'Prowadzenie zajęć w Szkole Głównej Handlowej z zakresu Strategii Zakupowych oraz Procesów Zakupowych - Katedra Logistyki SGH / Warsaw Executive MBA',
    ],
    selectedExperienceEN: [
      'Procurement improvements for a global leader in oilseed processing and the world’s largest producer of oils - development of a procurement spend tree, identification of savings potential and sourcing strategies in selected categories across 12 EMEA countries',
      'Procurement centralisation for a leading Polish automotive manufacturer - development of a central procurement spend tree, spend analysis, sourcing strategy development and implementation of savings across multiple categories',
      'Procurement optimisation for a food industry company - spend analysis, categorisation, sourcing strategies and implementation of PLN 5.9 million in annual savings',
      'Restructuring and implementation of a central procurement model, including securing PLN 300 million in savings',
      'Lecturing at the SGH Warsaw School of Economics on Procurement Strategies and Procurement Processes - Department of Logistics / Warsaw Executive MBA',
    ],
    type: 'leadership', featured: true, order: 2,
  },
  {
    id: 'monika-osiecka', slug: 'monika-osiecka', name: 'Monika Osiecka', role: 'Director / Head of People & Culture', roleEN: 'Director / Head of People & Culture',
    credentials: 'CIPS PEP Assessor · Trener · Coach', credentialsEN: 'CIPS PEP Assessor · Trainer · Coach', yearsExperience: '15+', imageUrl: '/images/website/Monika Osiecka.png', imagePosition: '50% 12%', linkedin: 'https://www.linkedin.com/in/monika-osiecka-940104125/',
    bio: 'Ponad 15 lat doświadczenia zawodowego w krajowych i międzynarodowych firmach sektora publicznego i prywatnego w obszarze doradztwa i zakupów.',
    bioEN: 'Over 15 years of professional experience with Polish and international organisations in the public and private sectors, spanning consulting and procurement.',
    areas: ['Petrochemia', 'Paliwa', 'Energetyka', 'Chemia', 'Budownictwo', 'Zakupy', 'Kategoryzacja i zarządzanie kategoriami', 'Restrukturyzacja organizacyjna', 'Rekrutacja', 'Komunikacja', 'Optymalizacja procesów', 'Szkolenia', 'Zarządzanie zmianą'],
    areasEN: ['Petrochemicals', 'Fuels', 'Energy', 'Chemicals', 'Construction', 'Procurement', 'Categorisation and category management', 'Organisational restructuring', 'Recruitment', 'Communication', 'Process optimisation', 'Training', 'Change management'],
    selectedExperience: [
      'Przygotowanie i prowadzenie Akademii Zakupowej dla działów zakupów i klientów wewnętrznych',
      'Przygotowanie i prowadzenie programu Ambasadorów Zmian w ramach zarządzania kompleksową zmianą w obszarze zakupów',
      'Szkolenia wewnętrzne dla kupców i klientów wewnętrznych w obszarze zakupów direct i indirect, w tym szkolenia onboardingowe',
      'Prowadzenie rekrutacji oraz opracowywanie zakresów obowiązków w obszarze zakupów',
      'Wdrażanie rozwiązań IT dla zakupów w międzynarodowych firmach oraz szkolenie kupców - Marketplanet, Logintrade, SAP Ariba oraz SAP MM',
      'Centralizacja funkcji zakupowej w obszarze zakupów direct i indirect',
      'Opracowywanie i wdrażanie procedur zakupowych, podręcznika budowania strategii kategorii oraz polityki SRM',
    ],
    selectedExperienceEN: [
      'Design and delivery of a Procurement Academy for procurement teams and internal clients',
      'Design and delivery of a Change Ambassadors programme supporting comprehensive change management within procurement',
      'Internal training for buyers and internal clients in direct and indirect procurement, including onboarding programmes',
      'Recruitment delivery and development of procurement role profiles and responsibilities',
      'Implementation of procurement IT solutions in international companies and buyer training - Marketplanet, Logintrade, SAP Ariba and SAP MM',
      'Centralisation of the procurement function across direct and indirect procurement',
      'Development and implementation of procurement procedures, a category strategy development handbook and an SRM policy',
    ],
    type: 'director', featured: true, order: 3,
  },
  {
    id: 'rafal-gilatowski', slug: 'rafal-gilatowski', name: 'Rafał Gilatowski', role: 'Director / Head of Digital', roleEN: 'Director / Head of Digital',
    imageUrl: '/images/website/Rafal Gilatowski.png', imagePosition: '50% 12%', linkedin: 'https://www.linkedin.com/in/rafal-gilatowski/',
    bio: 'Doświadczenie zawodowe w krajowych i międzynarodowych przedsiębiorstwach w obszarach audytu finansowego i konsultingu.',
    bioEN: 'Professional experience with Polish and international organisations in financial audit and consulting.',
    areas: ['Branża produkcyjna', 'Branża usługowa', 'Motoryzacja', 'FMCG', 'Budownictwo', 'Budowa modeli kosztowych kategorii zakupowych', 'Budowa strategii zakupowych', 'Strategie negocjacyjne', 'Restrukturyzacja organizacji i procesów zakupowych', 'Sourcing'],
    areasEN: ['Manufacturing', 'Services', 'Automotive', 'FMCG', 'Construction', 'Development of procurement category cost models', 'Procurement strategy development', 'Negotiation strategies', 'Restructuring of procurement organisations and processes', 'Sourcing'],
    selectedExperience: [
      'Opracowanie szeregu modeli kosztowych dla kategorii zakupowych oraz wykorzystanie ich w budowie strategii negocjacyjnych i strategii kategorii',
      'Budowa jednostki zakupowej wraz z opracowaniem procesów i strategii kategorii dla wiodącego przedsiębiorstwa z branży FMCG',
      'Interim management w wiodącej spółce farmaceutycznej w Polsce',
      'Realizacja prac sourcingowych dla kategorii indirect wraz z opracowaniem strategii negocjacyjnych dla wiodącego przedsiębiorstwa retail w Rumunii',
      'Przegląd i restrukturyzacja procesów w celu zwiększenia automatyzacji, ze szczególnym uwzględnieniem S2C i P2P, dla lidera branży retail w Polsce',
      'Opracowanie zasad rozliczania kosztów produkcji dla spółki medialnej',
      'Przeprowadzenie szeregu pełnych postępowań zakupowych optymalizujących łańcuchy dostaw i zwiększających efektywność działu zakupów',
      'Analiza rynku papierniczego w Polsce, prognoza rozwoju rynku oraz analiza europejskiego rynku poligraficznego',
    ],
    selectedExperienceEN: [
      'Development of cost models for multiple procurement categories and their use in negotiation and category strategy design',
      'Establishment of a procurement unit, including process and category strategy development, for a leading FMCG company',
      'Interim management for a leading pharmaceutical company in Poland',
      'Sourcing in indirect categories, including negotiation strategy development, for a leading retail company in Romania',
      'Process review and restructuring to increase automation, with particular focus on S2C and P2P, for a leading retail company in Poland',
      'Development of production cost allocation principles for a media company',
      'Delivery of end-to-end procurement processes to optimise supply chains and improve procurement function efficiency',
      'Analysis of the Polish paper market, a market development forecast and analysis of the European printing market',
    ],
    type: 'director', featured: true, order: 4,
  },
  {
    id: 'krzysztof-soltys', slug: 'krzysztof-soltys', name: 'Krzysztof Sołtys', role: 'Director', roleEN: 'Director', yearsExperience: '15+',
    imageUrl: '/images/website/Krzysztof Soltys bz.png', imagePosition: '50% 12%', linkedin: 'https://www.linkedin.com/in/krzysztof-so%C5%82tys/',
    bio: 'Ponad 15 lat doświadczenia zawodowego, m.in. w Ministerstwie Spraw Wewnętrznych i Administracji oraz Przedsiębiorstwie Państwowym „Porty Lotnicze” / Lotnisku Chopina.',
    bioEN: 'Over 15 years of professional experience, including roles at the Ministry of the Interior and Administration and Polish Airports State Enterprises / Warsaw Chopin Airport.',
    areas: ['Zakupy CAPEX i OPEX', 'Sektor produkcyjny', 'Sektor usługowy', 'Wdrażanie usprawnień w zakupach', 'Budowa strategii zakupowych', 'Kompleksowa realizacja procesów zakupowych', 'Szkolenia'],
    areasEN: ['CAPEX and OPEX procurement', 'Manufacturing sector', 'Services sector', 'Implementation of procurement improvements', 'Procurement strategy development', 'End-to-end procurement process delivery', 'Training'],
    professionalBackground: ['Ministerstwo Spraw Wewnętrznych i Administracji', 'Przedsiębiorstwo Państwowe „Porty Lotnicze” / Lotnisko Chopina'],
    professionalBackgroundEN: ['Ministry of the Interior and Administration', 'Polish Airports State Enterprises / Warsaw Chopin Airport'],
    type: 'director', featured: true, order: 5,
  },
  { id: 'agnieszka-tworzynska', slug: 'agnieszka-tworzynska', name: 'Agnieszka Tworzyńska', role: 'Training & Conferences', roleEN: 'Training & Conferences', type: 'trainer', featured: false, order: 6 },
  { id: 'tomasz-uscinski', slug: 'tomasz-uscinski', name: 'Tomasz Uściński', role: 'Head of Sales · SpendGuru', roleEN: 'Head of Sales · SpendGuru', email: 'tomasz.uscinski@profitia.pl', type: 'expert', featured: false, order: 7 },
]

/** Leadership and featured directors shown on About page */
export const FEATURED_TEAM: TeamMember[] = TEAM_MEMBERS
  .filter((member) => member.featured)
  .sort((a, b) => a.order - b.order)
