// ─────────────────────────────────────────────────────────
// CI-Profitia — Inline Advisory Block Registry
// All embedded advisory blocks — PL + EN, intent-aware,
// maturity-aware, section-targeted, executive-aware.
// ─────────────────────────────────────────────────────────

import type { AdvisoryBlock } from "@/types";

export const ADVISORY_BLOCK_REGISTRY: AdvisoryBlock[] = [

  // ══════════════════════════════════════════════════════
  // I1 — SAVINGS / COST REDUCTION
  // ══════════════════════════════════════════════════════

  {
    id: "AB-I1-01-pl",
    type: "insight",
    section: "capability_block",
    intents: ["I1_SAVINGS", "I8_NEGOTIATIONS"],
    maturityPersonas: ["reactive_buyer", "operational_buyer", "strategic_sourcer"],
    locale: "pl",
    headline: "Negocjacje cen to dopiero początek",
    body: "Firmy produkcyjne często zaczynają od rozmów o cenach, ale największy impact zwykle daje analiza should-cost i benchmarking dostawców. Pozwala to ustalić pozycję kosztową zanim wejdziesz do sali negocjacyjnej.",
    metric: { label: "Typowa poprawa marży", value: "3–8%" },
    cta: { label: "Zobacz jak działa Cost Scan", url: "/services/analiza-spot", type: "spot_analysis" },
    priority: 9,
    tags: ["cost", "savings", "should-cost", "negotiation"],
  },
  {
    id: "AB-I1-01-en",
    type: "insight",
    section: "capability_block",
    intents: ["I1_SAVINGS", "I8_NEGOTIATIONS"],
    maturityPersonas: ["reactive_buyer", "operational_buyer", "strategic_sourcer"],
    locale: "en",
    headline: "Price negotiation is just the start",
    body: "Companies often begin with price conversations, but the biggest cost impact usually comes from should-cost analysis and supplier benchmarking — establishing your cost position before entering the negotiation room.",
    metric: { label: "Typical margin improvement", value: "3–8%" },
    cta: { label: "See how Cost Scan works", url: "/services/analiza-spot", type: "spot_analysis" },
    priority: 9,
    tags: ["cost", "savings", "should-cost", "negotiation"],
  },

  {
    id: "AB-I1-02-pl",
    type: "executive_summary",
    section: "hero",
    intents: ["I1_SAVINGS"],
    maturityPersonas: ["executive_stakeholder"],
    locale: "pl",
    headline: "Wpływ zakupów na EBIT jest zazwyczaj niedoszacowany",
    body: "W organizacjach z spend zewnętrznym powyżej 200M PLN, poprawa kosztów zakupu o 2–3 punkty procentowe przekłada się bezpośrednio na wzrost EBIT — bez konieczności zwiększania sprzedaży.",
    metric: { label: "Dźwignia EBIT", value: "2–3pp = 15–25% EBIT growth" },
    cta: { label: "Porozmawiajmy o potencjale", url: "/contact", type: "contact_form" },
    priority: 10,
    executiveRoles: ["CFO", "CEO"],
    tags: ["ebit", "executive", "cost", "roi"],
  },
  {
    id: "AB-I1-02-en",
    type: "executive_summary",
    section: "hero",
    intents: ["I1_SAVINGS"],
    maturityPersonas: ["executive_stakeholder"],
    locale: "en",
    headline: "Procurement's impact on EBIT is typically underestimated",
    body: "In organisations with external spend above EUR 50M, improving procurement costs by 2–3 percentage points translates directly to EBIT growth — without needing to increase revenue.",
    metric: { label: "EBIT leverage", value: "2–3pp = 15–25% EBIT growth" },
    cta: { label: "Let's discuss the potential", url: "/contact", type: "contact_form" },
    priority: 10,
    executiveRoles: ["CFO", "CEO"],
    tags: ["ebit", "executive", "cost", "roi"],
  },

  {
    id: "AB-I1-03-pl",
    type: "benchmark",
    section: "benchmark",
    intents: ["I1_SAVINGS", "I2_FORECASTING"],
    maturityPersonas: ["strategic_sourcer", "advanced_analyst"],
    locale: "pl",
    headline: "Gdzie traciłeś w ostatnich 12 miesiącach?",
    body: "Analiza SPOT w 5–10 dni roboczych identyfikuje kategorie zakupowe z największym potencjałem oszczędnościowym. Średnio 3–6 kategorii w portfolio zakupowym kryje nieproporcjonalnie dużą część nieodzyskanego potencjału.",
    metric: { label: "Czas analizy", value: "5–10 dni roboczych" },
    cta: { label: "Zamów analizę SPOT", url: "/services/analiza-spot", type: "spot_analysis" },
    priority: 8,
    tags: ["spot", "diagnostic", "categories", "benchmark"],
  },
  {
    id: "AB-I1-03-en",
    type: "benchmark",
    section: "benchmark",
    intents: ["I1_SAVINGS", "I2_FORECASTING"],
    maturityPersonas: ["strategic_sourcer", "advanced_analyst"],
    locale: "en",
    headline: "Where did you leave value on the table in the last 12 months?",
    body: "SPOT Analysis identifies your highest-potential spend categories in 5–10 working days. On average, 3–6 categories in a procurement portfolio hide a disproportionate share of unrealised savings potential.",
    metric: { label: "Analysis turnaround", value: "5–10 working days" },
    cta: { label: "Order a SPOT Analysis", url: "/services/analiza-spot", type: "spot_analysis" },
    priority: 8,
    tags: ["spot", "diagnostic", "categories", "benchmark"],
  },

  // ══════════════════════════════════════════════════════
  // I3 — SUPPLIER RISK
  // ══════════════════════════════════════════════════════

  {
    id: "AB-I3-01-pl",
    type: "risk_insight",
    section: "capability_block",
    intents: ["I3_SUPPLIER_RISK"],
    maturityPersonas: ["operational_buyer", "strategic_sourcer", "advanced_analyst", "executive_stakeholder"],
    locale: "pl",
    headline: "Problem pojawia się przed awarią dostawcy, nie po niej",
    body: "W wielu organizacjach problem staje się widoczny dopiero gdy dostawca przestaje realizować dostawy. Supplier Intelligence pozwala wykrywać sygnały finansowego ryzyka wcześniej — na podstawie danych bilansowych i wskaźników rynkowych.",
    metric: { label: "Wyprzedzenie detekcji ryzyka", value: "3–9 miesięcy" },
    cta: { label: "Zobacz Supplier Intelligence", url: "/services/supplier-intelligence", type: "service_order" },
    priority: 9,
    tags: ["supplier-risk", "intelligence", "continuity", "early-warning"],
  },
  {
    id: "AB-I3-01-en",
    type: "risk_insight",
    section: "capability_block",
    intents: ["I3_SUPPLIER_RISK"],
    maturityPersonas: ["operational_buyer", "strategic_sourcer", "advanced_analyst", "executive_stakeholder"],
    locale: "en",
    headline: "The problem surfaces before supplier failure, not after",
    body: "In many organisations, risk only becomes visible when a supplier stops delivering. Supplier Intelligence detects financial risk signals earlier — based on balance sheet data and market indicators.",
    metric: { label: "Risk detection lead time", value: "3–9 months" },
    cta: { label: "See Supplier Intelligence", url: "/services/supplier-intelligence", type: "service_order" },
    priority: 9,
    tags: ["supplier-risk", "intelligence", "continuity", "early-warning"],
  },

  {
    id: "AB-I3-02-pl",
    type: "executive_summary",
    section: "proof_point",
    intents: ["I3_SUPPLIER_RISK"],
    maturityPersonas: ["executive_stakeholder", "transformation_leader"],
    locale: "pl",
    headline: "Ryzyko dostawcy to ryzyko biznesowe",
    body: "Utrata kluczowego dostawcy to nie problem zakupowy — to ryzyko łańcucha wartości. Regularne monitorowanie kondycji finansowej dostawców C i D pozwala uniknąć nieplanowanych przestojów produkcyjnych.",
    cta: { label: "Porozmawiajmy o ryzyku", url: "/contact", type: "contact_form" },
    priority: 8,
    executiveRoles: ["CEO", "CPO", "CFO"],
    tags: ["executive", "risk", "supply-chain", "continuity"],
  },
  {
    id: "AB-I3-02-en",
    type: "executive_summary",
    section: "proof_point",
    intents: ["I3_SUPPLIER_RISK"],
    maturityPersonas: ["executive_stakeholder", "transformation_leader"],
    locale: "en",
    headline: "Supplier risk is business risk",
    body: "Losing a critical supplier is not a procurement problem — it's a value chain risk. Regular financial health monitoring of C and D-grade suppliers prevents unplanned production stoppages.",
    cta: { label: "Let's talk about risk", url: "/contact", type: "contact_form" },
    priority: 8,
    executiveRoles: ["CEO", "CPO", "CFO"],
    tags: ["executive", "risk", "supply-chain", "continuity"],
  },

  // ══════════════════════════════════════════════════════
  // I8 — NEGOTIATIONS
  // ══════════════════════════════════════════════════════

  {
    id: "AB-I8-01-pl",
    type: "insight",
    section: "capability_block",
    intents: ["I8_NEGOTIATIONS", "I1_SAVINGS"],
    maturityPersonas: ["operational_buyer", "strategic_sourcer"],
    locale: "pl",
    headline: "Skuteczna negocjacja zaczyna się od faktów",
    body: "Skuteczna negocjacja wymaga faktów, nie intuicji. Should-cost analysis daje Ci pozycję kosztową przed wejściem do sali negocjacyjnej — wiesz ile powinien kosztować produkt i gdzie jest marża dostawcy.",
    metric: { label: "Dodatkowe oszczędności negocjacyjne", value: "+4–12%" },
    cta: { label: "Umów workshop negocjacyjny", url: "/education/warsztaty-negocjacyjne", type: "workshop" },
    priority: 9,
    tags: ["negotiation", "should-cost", "facts", "preparation"],
  },
  {
    id: "AB-I8-01-en",
    type: "insight",
    section: "capability_block",
    intents: ["I8_NEGOTIATIONS", "I1_SAVINGS"],
    maturityPersonas: ["operational_buyer", "strategic_sourcer"],
    locale: "en",
    headline: "Effective negotiation starts with facts",
    body: "Effective negotiation requires facts, not intuition. Should-cost analysis gives you the cost position before entering the negotiation room — you know what a product should cost and where the supplier's margin lies.",
    metric: { label: "Additional negotiation savings", value: "+4–12%" },
    cta: { label: "Book a negotiation workshop", url: "/education/warsztaty-negocjacyjne", type: "workshop" },
    priority: 9,
    tags: ["negotiation", "should-cost", "facts", "preparation"],
  },

  {
    id: "AB-I8-02-pl",
    type: "workshop_prompt",
    section: "workshop",
    intents: ["I8_NEGOTIATIONS", "I6_EDUCATION"],
    maturityPersonas: ["operational_buyer", "strategic_sourcer", "advanced_analyst"],
    locale: "pl",
    headline: "Twój zespół jest gotowy na trudne negocjacje?",
    body: "Harvard-methodology — w realistycznych scenariuszach i case studies. Workshop jest zaprojektowany dla kupców i category managerów, którzy chcą wejść na kolejny poziom skuteczności negocjacyjnej.",
    cta: { label: "Zapytaj o program", url: "/education/warsztaty-negocjacyjne", type: "workshop" },
    priority: 7,
    tags: ["workshop", "team", "negotiation", "harvard"],
  },
  {
    id: "AB-I8-02-en",
    type: "workshop_prompt",
    section: "workshop",
    intents: ["I8_NEGOTIATIONS", "I6_EDUCATION"],
    maturityPersonas: ["operational_buyer", "strategic_sourcer", "advanced_analyst"],
    locale: "en",
    headline: "Is your team ready for difficult negotiations?",
    body: "Harvard methodology — in realistic scenarios and case studies. Designed for buyers and category managers who want to reach the next level of negotiation effectiveness.",
    cta: { label: "Ask about the programme", url: "/education/warsztaty-negocjacyjne", type: "workshop" },
    priority: 7,
    tags: ["workshop", "team", "negotiation", "harvard"],
  },

  // ══════════════════════════════════════════════════════
  // I5 — SOURCING / STRATEGY
  // ══════════════════════════════════════════════════════

  {
    id: "AB-I5-01-pl",
    type: "insight",
    section: "capability_block",
    intents: ["I5_SOURCING"],
    maturityPersonas: ["strategic_sourcer", "advanced_analyst", "transformation_leader"],
    locale: "pl",
    headline: "Category strategy to nie projekt — to sposób zarządzania portfelem",
    body: "Budowanie strategii kategorii zakupowych to ciągłe zarządzanie portfelem z perspektywą wartości i ryzyka. Organizacje z dojrzałą category strategy osiągają o 30% wyższą skuteczność negocjacyjną i lepszą przewidywalność kosztów.",
    metric: { label: "Wyższa skuteczność negocjacyjna", value: "+30%" },
    cta: { label: "Poznaj podejście Profitia", url: "/services/category-strategy", type: "service_order" },
    priority: 8,
    tags: ["category-strategy", "sourcing", "portfolio", "maturity"],
  },
  {
    id: "AB-I5-01-en",
    type: "insight",
    section: "capability_block",
    intents: ["I5_SOURCING"],
    maturityPersonas: ["strategic_sourcer", "advanced_analyst", "transformation_leader"],
    locale: "en",
    headline: "Category strategy is not a project — it's portfolio management",
    body: "Building category strategies is continuous portfolio management with a value and risk perspective. Organisations with mature category strategies achieve 30% higher negotiation effectiveness and better cost predictability.",
    metric: { label: "Higher negotiation effectiveness", value: "+30%" },
    cta: { label: "Explore Profitia's approach", url: "/services/category-strategy", type: "service_order" },
    priority: 8,
    tags: ["category-strategy", "sourcing", "portfolio", "maturity"],
  },

  // ══════════════════════════════════════════════════════
  // I2 — FORECASTING / SPEND ANALYTICS
  // ══════════════════════════════════════════════════════

  {
    id: "AB-I2-01-pl",
    type: "insight",
    section: "capability_block",
    intents: ["I2_FORECASTING", "I1_SAVINGS"],
    maturityPersonas: ["operational_buyer", "strategic_sourcer", "advanced_analyst"],
    locale: "pl",
    headline: "Spend analytics to nie raportowanie — to system decyzyjny",
    body: "Pytanie brzmi: co Twoja organizacja może przewidzieć z 3-miesięcznym wyprzedzeniem? Spend Cube i dashboardy procurement to podstawa do fact-based negotiation — bez danych, bez dźwigni negocjacyjnej.",
    metric: { label: "Widoczność spend", value: "kategoria → dostawca → SKU" },
    cta: { label: "Zobacz Spend Cube", url: "/services/spend-cube", type: "service_order" },
    priority: 8,
    tags: ["spend-analytics", "forecasting", "data", "visibility"],
  },
  {
    id: "AB-I2-01-en",
    type: "insight",
    section: "capability_block",
    intents: ["I2_FORECASTING", "I1_SAVINGS"],
    maturityPersonas: ["operational_buyer", "strategic_sourcer", "advanced_analyst"],
    locale: "en",
    headline: "Spend analytics is not reporting — it's a decision system",
    body: "The question is: what can your organisation predict 3 months ahead? Spend Cube and procurement dashboards are the foundation for fact-based negotiation — without data, there is no negotiation leverage.",
    metric: { label: "Spend visibility", value: "category → supplier → SKU" },
    cta: { label: "See Spend Cube", url: "/services/spend-cube", type: "service_order" },
    priority: 8,
    tags: ["spend-analytics", "forecasting", "data", "visibility"],
  },

  // ══════════════════════════════════════════════════════
  // I6 — EDUCATION
  // ══════════════════════════════════════════════════════

  {
    id: "AB-I6-01-pl",
    type: "workshop_prompt",
    section: "workshop",
    intents: ["I6_EDUCATION"],
    maturityPersonas: ["reactive_buyer", "operational_buyer", "strategic_sourcer"],
    locale: "pl",
    headline: "Program edukacyjny dostosowany do Twojej organizacji",
    body: "In-company procurement programmes są projektowane pod konkretne realia — branżę, model zakupowy, stan dojrzałości i priorytety strategiczne. Uczymy na realnych przypadkach Twojej organizacji.",
    cta: { label: "Zaprojektuj program in-company", url: "/education/in-company-workshops", type: "workshop" },
    priority: 7,
    tags: ["education", "in-company", "programme", "development"],
  },
  {
    id: "AB-I6-01-en",
    type: "workshop_prompt",
    section: "workshop",
    intents: ["I6_EDUCATION"],
    maturityPersonas: ["reactive_buyer", "operational_buyer", "strategic_sourcer"],
    locale: "en",
    headline: "An education programme tailored to your organisation",
    body: "In-company procurement programmes are designed around your specific reality — industry, procurement model, maturity stage and strategic priorities. We teach using real cases from your organisation.",
    cta: { label: "Design an in-company programme", url: "/education/in-company-workshops", type: "workshop" },
    priority: 7,
    tags: ["education", "in-company", "programme", "development"],
  },

  // ══════════════════════════════════════════════════════
  // I4 — DIGITALIZATION
  // ══════════════════════════════════════════════════════

  {
    id: "AB-I4-01-pl",
    type: "insight",
    section: "capability_block",
    intents: ["I4_DIGITALIZATION"],
    maturityPersonas: ["strategic_sourcer", "advanced_analyst", "transformation_leader"],
    locale: "pl",
    headline: "Digitalizacja zakupów zaczyna się od danych, nie od systemu",
    body: "Organizacje, które próbują wdrożyć system bez porządku w danych, kupują problem za 7-cyfrową kwotę. Procurement transformation zaczyna się od mapy procesów i governance — system jest kolejnym krokiem.",
    cta: { label: "Poznaj podejście transformacyjne", url: "/services/procurement-transformation", type: "service_order" },
    priority: 7,
    tags: ["digitalization", "transformation", "process", "data"],
  },
  {
    id: "AB-I4-01-en",
    type: "insight",
    section: "capability_block",
    intents: ["I4_DIGITALIZATION"],
    maturityPersonas: ["strategic_sourcer", "advanced_analyst", "transformation_leader"],
    locale: "en",
    headline: "Procurement digitalisation starts with data, not the system",
    body: "Organisations that try to implement a system without data clarity are buying a 7-figure problem. Procurement transformation starts with process mapping and governance — the system is the next step.",
    cta: { label: "Explore the transformation approach", url: "/services/procurement-transformation", type: "service_order" },
    priority: 7,
    tags: ["digitalization", "transformation", "process", "data"],
  },

  // ══════════════════════════════════════════════════════
  // GENERIC — PROOF POINT / ROI
  // ══════════════════════════════════════════════════════

  {
    id: "AB-GEN-01-pl",
    type: "proof_point",
    section: "proof_point",
    intents: ["I1_SAVINGS", "I8_NEGOTIATIONS", "I3_SUPPLIER_RISK", "I5_SOURCING", "I2_FORECASTING"],
    maturityPersonas: ["reactive_buyer", "operational_buyer", "strategic_sourcer", "advanced_analyst", "executive_stakeholder", "transformation_leader"],
    locale: "pl",
    headline: "Projekty z weryfikowalnym ROI",
    body: "Profitia pracuje wyłącznie w oparciu o fakty — analizę danych, benchmarki rynkowe i udokumentowane wyniki. Każdy projekt zaczyna się od diagnozy obecnego stanu i mierzalnych celów.",
    cta: { label: "Porozmawiajmy", url: "/contact", type: "contact_form" },
    priority: 5,
    tags: ["proof", "roi", "results", "credibility"],
  },
  {
    id: "AB-GEN-01-en",
    type: "proof_point",
    section: "proof_point",
    intents: ["I1_SAVINGS", "I8_NEGOTIATIONS", "I3_SUPPLIER_RISK", "I5_SOURCING", "I2_FORECASTING"],
    maturityPersonas: ["reactive_buyer", "operational_buyer", "strategic_sourcer", "advanced_analyst", "executive_stakeholder", "transformation_leader"],
    locale: "en",
    headline: "Projects with verifiable ROI",
    body: "Profitia works exclusively based on facts — data analysis, market benchmarks and documented results. Every project starts with a current-state diagnostic and measurable objectives.",
    cta: { label: "Let's talk", url: "/contact", type: "contact_form" },
    priority: 5,
    tags: ["proof", "roi", "results", "credibility"],
  },

  {
    id: "AB-GEN-02-pl",
    type: "roi_insight",
    section: "roi_block",
    intents: ["I1_SAVINGS", "I8_NEGOTIATIONS"],
    maturityPersonas: ["executive_stakeholder", "transformation_leader"],
    locale: "pl",
    headline: "Zwrot z inwestycji w procurement advisory",
    body: "Projekty Profitia generują zwrot z inwestycji w przedziale 3–12 miesiące od zakończenia. W projektach should-cost i negocjacyjnych zwrot pojawia się często już w pierwszej rundzie negocjacji.",
    metric: { label: "Typowy ROI timeline", value: "3–12 miesięcy" },
    cta: { label: "Omów swój case", url: "/contact", type: "contact_form" },
    priority: 8,
    executiveRoles: ["CFO", "CEO", "CPO"],
    tags: ["roi", "executive", "investment", "payback"],
  },
  {
    id: "AB-GEN-02-en",
    type: "roi_insight",
    section: "roi_block",
    intents: ["I1_SAVINGS", "I8_NEGOTIATIONS"],
    maturityPersonas: ["executive_stakeholder", "transformation_leader"],
    locale: "en",
    headline: "Return on investment in procurement advisory",
    body: "Profitia projects generate ROI within 3–12 months of completion. In should-cost and negotiation projects, the return often appears in the first negotiation round.",
    metric: { label: "Typical ROI timeline", value: "3–12 months" },
    cta: { label: "Discuss your case", url: "/contact", type: "contact_form" },
    priority: 8,
    executiveRoles: ["CFO", "CEO", "CPO"],
    tags: ["roi", "executive", "investment", "payback"],
  },

  // ══════════════════════════════════════════════════════
  // DIAGNOSTIC QUESTIONS — surface intent early
  // ══════════════════════════════════════════════════════

  {
    id: "AB-DIAG-01-pl",
    type: "diagnostic_question",
    section: "hero",
    intents: ["I7_EXPLORATORY", "UNKNOWN"],
    maturityPersonas: ["reactive_buyer", "operational_buyer", "unknown"],
    locale: "pl",
    headline: "Gdzie zaczyna się Twój problem zakupowy?",
    body: "Wiele organizacji traci wartość w 2–3 obszarach jednocześnie: ceny dostawców, brak danych do negocjacji, ryzyko ciągłości. Krótka rozmowa wystarczy żeby ustalić priorytety.",
    cta: { label: "Zacznij rozmowę", url: "/contact", type: "contact_form" },
    priority: 6,
    tags: ["diagnostic", "discovery", "exploratory"],
  },
  {
    id: "AB-DIAG-01-en",
    type: "diagnostic_question",
    section: "hero",
    intents: ["I7_EXPLORATORY", "UNKNOWN"],
    maturityPersonas: ["reactive_buyer", "operational_buyer", "unknown"],
    locale: "en",
    headline: "Where does your procurement problem begin?",
    body: "Many organisations lose value in 2–3 areas simultaneously: supplier prices, lack of data for negotiation, continuity risk. A short conversation is enough to establish priorities.",
    cta: { label: "Start a conversation", url: "/contact", type: "contact_form" },
    priority: 6,
    tags: ["diagnostic", "discovery", "exploratory"],
  },
];
